version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: imghost-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  imghost:
    build: .
    container_name: imghost-app
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET=imghost-files
      - MINIO_USE_SSL=false
    depends_on:
      - minio
    volumes:
      - ./uploads:/app/uploads
      - ./encrypted:/app/encrypted

volumes:
  minio_data:
