version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: imghost-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    # networks:
    #   - network1

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio-data:
# networks:
#   network1:
#     name: my-network
